### ISSUE TITLE
Resizeable text area

### ISSUE THREAD

**Issue by wilhelmberg** [skeenp/QGIS3-getWKT#2]
Great plugin, just what I was looking for 😄 

Would be great if the WKT text area would resize with the dialog to be able to get a better overview of the data:

![image](https://user-images.githubusercontent.com/4549888/54816949-f07be400-4c95-11e9-84be-d3c99233a41d.png)

**Comment by skeenp** [comment]
Sorry for the delay, I've updated the GUI in the latest version (pending plugin repo upload) to auto resize. It won't remember the new size next time, would have to go back to the books for that one but could be achieved
