### ISSUE TITLE
Bug with QGIS 3.8

### ISSUE THREAD

**Issue by jbdesbas** [skeenp/QGIS3-getWKT#3]
Hi,
The plugin seem to not works with QGIS 3.8. 
The text area display : 

> ERROR: Layer selected is not vector

**Comment by jsparedes** [comment]
Hello, the same problem described by @jbdesbas with QGIS 3.8.1-Zanzibar

**Comment by skeenp** [comment]
Bugger, am moving house at the moment and my dev PC is in storage. I'll get onto this asap though.

**Comment by skeenp** [comment]
Sorry for the delay, I've added the suggestion by @imajic-unimelb to the latest version (pending plugin repo upload).
