### ISSUE TITLE
Python Error Running Get WKT

### ISSUE THREAD

**Issue by RCGIC** [skeenp/QGIS3-getWKT#7]
Getting the following Python Error when I run the plugin to get a polygon's WKT. Running QGIS 3.16.2 and Python 3.7

> An error has occurred while executing Python code: 
> 
> TypeError: QgsGeometry.asWkt(): argument 1 has unexpected type 'str' 
> Traceback (most recent call last):
>   File "C:/Users/rwcar/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\QGIS3-getWKT\getwkt3.py", line 212, in run_wkt
>     self.run('wkt')
>   File "C:/Users/rwcar/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\QGIS3-getWKT\getwkt3.py", line 287, in run
>     wkt = geom.asWkt(dp_count) if dp_count else geom.asWkt()
> TypeError: QgsGeometry.asWkt(): argument 1 has unexpected type 'str'
> 
> 
> Python version: 3.7.0 (v3.7.0:1bf9cc5093, Jun 27 2018, 04:59:51) [MSC v.1914 64 bit (AMD64)] 
> QGIS version: 3.16.2-Hannover Hannover, f1660f9da5 
> 
> Python Path:
> C:/PROGRA~1/QGIS3~1.16/apps/qgis/./python
> C:/Users/rwcar/AppData/Roaming/QGIS/QGIS3\profiles\default/python
> C:/Users/rwcar/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins
> C:/PROGRA~1/QGIS3~1.16/apps/qgis/./python/plugins
> C:\PROGRA~1\QGIS3~1.16\apps\Python37
> C:\PROGRA~1\QGIS3~1.16\apps\Python37\Scripts
> C:\Program Files\QGIS 3.16\bin\python37.zip
> C:\PROGRA~1\QGIS3~1.16\apps\Python37\DLLs
> C:\PROGRA~1\QGIS3~1.16\apps\Python37\lib
> C:\Program Files\QGIS 3.16\bin
> C:\PROGRA~1\QGIS3~1.16\apps\Python37\lib\site-packages
> C:\PROGRA~1\QGIS3~1.16\apps\Python37\lib\site-packages\win32
> C:\PROGRA~1\QGIS3~1.16\apps\Python37\lib\site-packages\win32\lib
> C:\PROGRA~1\QGIS3~1.16\apps\Python37\lib\site-packages\Pythonwin
> C:/Users/rwcar/AppData/Roaming/QGIS/QGIS3\profiles\default/python
> C:\Users\rwcar\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\kmltools\libs
> .
> C:\Users\rwcar\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\vector_tiles_reader\ext-libs
> C:/Users/rwcar/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\vrtbuilderplugin
> C:\Users\rwcar\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\vrtbuilderplugin\vrtbuilder
> C:/Users/rwcar/Desktop

**Comment by skeenp** [comment]
Interesting, in some cases the saved setting for precision is not being read as an integer even though it is being saved as one. I've added in an error handle which will capture the setting not being of integer type, defaulting to 17 when an issue occurs. I'll test and submit to the plugin repo in the next couple of days.

**Comment by skeenp** [comment]
Updated an published. Issue should now be fixed.

**Comment by RCGIC** [comment]
Thanks @skeenp. Just downloaded the update and I can confirm it now works correctly with the decimal places set on my system. Regards
