### ISSUE TITLE
Feature Request: Keep Only One Button to Front. Move Rest to Dropdown.

### ISSUE THREAD

**Issue by ar-siddiqui** [skeenp/QGIS3-getWKT#9]
![image](https://user-images.githubusercontent.com/53625184/114089152-ce0c9180-9883-11eb-9598-b447631c0348.png)

This plugin is really good but it occupies too much space for small functionality that is not used often. I would suggest reducing the space buttons occupy by having a setup like what QGIS has for Deselect Features. See Picture.

It is important to me because I have many plugins installed. Thanks

**Comment by skeenp** [comment]
Great idea and sorry for the delay, will be released as a feature in the next version which should be made available in the next day or two.

**Comment by skeenp** [comment]
Applied in latest update now available at https://plugins.qgis.org/plugins/QGIS3-getWKT/
